version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - "SPRING_PROFILES_ACTIVE=postgres,random-scheduler"
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=opensesame
      - POSTGRES_PASSWORD=opensesame
      - POSTGRES_DB=appointmentdb
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U opensesame -d appointmentdb -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 3